Core2TP.UI.MVC/Controllers/OrdersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Core2TP.DATA.EF.Models;

namespace Core2TP.UI.MVC.Controllers
{
    public class OrdersController : Controller
    {
        private readonly gadgetstoreContext _context;

        public OrdersController(gadgetstoreContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var gadgetstoreContext = _context.Orders.Include(o => o.User);
            return View(await gadgetstoreContext.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.UserDetails, "UserId", "UserId");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,UserId,OrderDate,ShipToName,ShipCity,ShipState,ShipZip")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.UserDetails, "UserId", "UserId", order.UserId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.UserDetails, "UserId", "UserId", order.UserId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,UserId,OrderDate,ShipToName,ShipCity,ShipState,ShipZip")] Order order)
        {
            if (id != order.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.UserDetails, "UserId", "UserId", order.UserId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.OrderId == id);
        }
    }
}

Core2TP.UI.MVC/Controllers/ProductsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Core2TP.DATA.EF.Models;
using System.Drawing;
using Core2TP.UI.MVC.Utilities;
using X.PagedList;

namespace Core2TP.UI.MVC.Controllers
{
    public class ProductsController : Controller
    {
        private readonly gadgetstoreContext _context;
        //added for access to wwwroot folder
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductsController(gadgetstoreContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Products
        //Table view
        public async Task<IActionResult> Index()
        {
            #region LINQ Notes
            //_context.Products --> returns a ***collection*** of ALL products from the table

            /*
             * LINQ - 2 Syntaxes
             * Method Syntax: uses C# methods and lambda expressions
             * Query (Keyword) Syntax: uses SQL keywords
             * - Ultimately, it doesn't matter which syntax you choose - you can accomplish whatever you need with either.
             * - For learning effectiveness, practice primarily with the one that makes most sense to you.  Once you feel you have a good grasp,
             * try the same problems with the other syntax.
             * 
             * METHOD SYNTAX EXAMPLE
             * var [filteredCollection] = _context.[Entity].Where([otf] => [otf].[Property] [[Condition]]).ToListAsync();
             * 
             * 
             * KEYWORD SYNTAX EXAMPLE
             * var [filteredCollection] = (from [otf] in _context.[Entity]
             *                            where [otf].[Property] [[Condition]]
             *                            select [otf]).ToListAsync();
             * 
             * - filteredCollection --> the resulting collection once you filter out records you do not need
             * - Entity --> the specific DB table you are retrieving results from
             * - otf --> an on-the-fly variable created by you to represent a single Entity from the table
             * - Property --> the property from the Entity to be evaluated in the condition
             * - Condition --> your filter criteria
             * */
            #endregion

            //Original code scaffolded by EF
            var products = _context.Products.Include(p => p.Category).Include(p => p.Supplier).Include(p => p.OrderProducts);

            //Use LINQ to filter this so we only see 'active' Products (aka products that are NOT discontinued)
            //Filtered collection using LINQ
            //var products = _context.Products.Where(p => !p.IsDiscontinued).Include(p => p.Category).Include(p => p.Supplier);

            #region More LINQ Examples
            //More examples of filtering products
            //Typically, these filters would be applied dynamically based on user input (search form, checkboxes, drop down lists...)
            //We will add that functionality in next week.  For now, we are going to focus on JUST delivering filtered results

            //Only show Products in the 'weapon' category
            //var products = _context.Products.Where(p => p.Category.CategoryName.ToLower() == "weapon").Include(p => p.Category).Include(p => p.Supplier);

            //Only show Products made by 'Marvelous Artifacts'
            //var products = _context.Products.Where(p => p.Supplier.SupplierName.ToLower().Contains("marvelous"))
            //    .Include(p => p.Category)
            //    .Include(p => p.Supplier);

            //Show products that are out of stock and pending reorder
            //var products = _context.Products.Where(p => p.UnitsInStock == 0 && p.UnitsOnOrder > 0)
            //    .Include(p => p.Category)
            //    .Include(p => p.Supplier);

            //MINI LAB!
            //Show products that cost more than $500

            //Show all products that are a 'Tool' from 'United Federation of Planets'

            //Show all products that contain the word 'star' in the name
            #endregion

            return View(await products.ToListAsync());
        }



        #region Filter/Paging Steps
        //---- SEARCH TEXTBOX ----//
        //1) Create form in the view (for the SEARCH portion, only need 1 textbox and a submit button - <select> will be added later)
        //2) Update controller Action ([A] add param, [B]add search filter logic)

        //---- CATEGORY DDL ----//
        //3) Create ViewData[] object in Controller action (this sends DDL list to the View)
        //4) Add <select> inside of <form>
        //5) Update Controller Action ([A] add param, [B] add category filter logic)

        //---- PAGED LIST ----//
        //6) Install package for X.PagedList.Mvc.Core
        //7) Add using statements and update model declaration in the View
        //8) Add param to Controller Action
        //9) Add page size variable in Action
        //10) Update return statement in Controller Action
        //11) Add Counter in View

        // 12) Create a new CSS file in wwwroot/css named 'PagedList.css'
        //      - NOTE: may need to go to the package's NuGet page and copy the CSS directly OR copy from an existing project :)
        //      - X.PagedList CSS file link (go here to copy the code): https://github.com/dncuug/X.PagedList/blob/master/examples/X.PagedList.Mvc.Example.Core/wwwroot/css/PagedList.css
        // 13) Add a <link> to the _Layout referencing 'PagedList.css'
        #endregion


        //Tile view
        //                                            **** STEP 2.A ****,  **** STEP 5.A ****, **** STEP 8 ****
        public async Task<IActionResult> TiledProducts(string searchTerm, int categoryId = 0, int page = 1)//added params for query
        {
            //**** STEP 9 ****//
            int pageSize = 6;//allows us to set how many records per page

            //**** STEP 3 ****//
            //List of Categories to return to the view for DDL population
            //NOTE: copied code from Products/Create to generate DDL
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");
            ViewBag.Category = 0;

            //Main list of products - anything that is not discontinued. 
            //If filters are incorporated, we will whittle this list down
            var products = _context.Products.Where(p => !p.IsDiscontinued).Include(p => p.Category).Include(p => p.Supplier).OrderBy(p => p.ProductName).ToList();

            //**** STEP 5.B ****/
            //Filter by category first
            #region Optional Category Filter
            if (categoryId != 0)
            {
                products = products.Where(p => p.CategoryId == categoryId).ToList();
                //Regenerate ddl so that the current item is still 'selected'
                ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", categoryId);
                ViewBag.Category = categoryId;
            }
            #endregion

            //**** Step 2.B ****/
            //Filter by search term second
            #region Optional Search Filter
            if (!String.IsNullOrEmpty(searchTerm))
            {
                //if optional search is used, then filter results by the searchTerm - like a fuzzy search
                products = products
                    .Where(p => p.ProductName.ToLower().Contains(searchTerm.ToLower()) || 
                                p.ProductDescription.ToLower().Contains(searchTerm.ToLower()) ||
                                p.Category.CategoryName.ToLower().Contains(searchTerm.ToLower()) ||
                                p.Supplier.SupplierName.ToLower().Contains(searchTerm.ToLower()))
                    .ToList();

                //Pass the searchTerm back to the view to verify what the user searched for
                ViewBag.SearchTerm = searchTerm;
            }
            else
            {
                ViewBag.SearchTerm = null;
            }
            #endregion

            //OG
            //return View(products.ToList());

            //**** STEP 10 *****//
            return View(products.ToPagedList(page, pageSize));
        }
        

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.Supplier)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");
            ViewData["SupplierId"] = new SelectList(_context.Suppliers, "SupplierId", "Address");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,ProductPrice,ProductDescription,UnitsInStock,UnitsOnOrder,IsDiscontinued,CategoryId,SupplierId,ProductImage,Image")] Product product)
        {
            //NOTE: RUN THROUGH THIS WITHOUT MODIFYING THE Product.cs MODEL FIRST - walk through debugger and show why we are not passing model validation

Core2TP.UI.MVC/Views/Shared/_Layout.cshtml
@*ALWAYS add the two lines below*@
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html>
<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="shortcut icon" href="images/favicon.png" type="">
    <title>@ViewData["Title"] - Core 2</title>
    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />
    <!-- font awesome style -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/css/responsive.css" rel="stylesheet" />

    <!--DataTables styles-->
    <link href="//cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css" rel="stylesheet" />

    <!-- Paged List Styles -->
    @* STEP 13 *@
    <link href="~/css/PagedList.css" rel="stylesheet" />

    <link href="~/css/custom.css" rel="stylesheet" />
</head>
<body>
    <div class="hero_area">
        <!-- header section strats -->
        <header class="header_section">
            <div class="container">
                <nav class="navbar navbar-expand-lg custom_nav-container ">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img width="250" src="~/images/corelogo.png" alt="#" /></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class=""> </span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav">
                            <li class="nav-item active">
                                <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
                                    <span class="nav-label">Notes <span class="caret"></span></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a asp-controller="Notes" asp-action="Identity">Identity</a></li>
                                    <li><a asp-controller="Notes" asp-action="EntityFramework">Entity Framework (EF)</a></li>
                                    <li><a asp-controller="Notes" asp-action="Metadata">Metadata</a></li>
                                    <li><a asp-controller="Notes" asp-action="Security">Security</a></li>
                                    <li><a asp-controller="Notes" asp-action="ViewCleanup">ViewCleanup</a></li>
                                </ul>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
                                    <span class="nav-label">Admin <span class="carret"></span></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a asp-controller="Suppliers" asp-action="Index">Suppliers</a>
                                    </li>
                                    <li>
                                        <a asp-controller="Categories" asp-action="Index">Categories</a>
                                    </li>
                                    <li>
                                        <a asp-controller="OrderProducts" asp-action="Index">Order/Products</a>
                                    </li>
                                    <li>
                                        <a asp-controller="Administration" asp-action="ListUsers">Users</a>
                                    </li>
                                    <li>
                                        <a asp-controller="Administration" asp-action="ListRoles">Roles</a>
                                    </li>
                                </ul>
                            </li>

                            <partial name="_LoginPartial" />

                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Products" asp-action="Index">Shop</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Orders" asp-action="Index">Orders</a>
                            </li>


                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="Contact">
                                    Contact
                                </a>
                            </li>




                            

                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 456.029 456.029" style="enable-background:new 0 0 456.029 456.029;" xml:space="preserve">
                                    <g>
                                    <g>
                                    <path d="M345.6,338.862c-29.184,0-53.248,23.552-53.248,53.248c0,29.184,23.552,53.248,53.248,53.248
                                          c29.184,0,53.248-23.552,53.248-53.248C398.336,362.926,374.784,338.862,345.6,338.862z" />
                                    </g>
                                 </g>
                                    <g>
                                    <g>
                                    <path d="M439.296,84.91c-1.024,0-2.56-0.512-4.096-0.512H112.64l-5.12-34.304C104.448,27.566,84.992,10.67,61.952,10.67H20.48
                                          C9.216,10.67,0,19.886,0,31.15c0,11.264,9.216,20.48,20.48,20.48h41.472c2.56,0,4.608,2.048,5.12,4.608l31.744,216.064
                                          c4.096,27.136,27.648,47.616,55.296,47.616h212.992c26.624,0,49.664-18.944,55.296-45.056l33.28-166.4
                                          C457.728,97.71,450.56,86.958,439.296,84.91z" />
                                    </g>
                                 </g>
                                    <g>
                                    <g>
                                    <path d="M215.04,389.55c-1.024-28.16-24.576-50.688-52.736-50.688c-29.696,1.536-52.224,26.112-51.2,55.296
                                          c1.024,28.16,24.064,50.688,52.224,50.688h1.024C193.536,443.31,216.576,418.734,215.04,389.55z" />
                                    </g>
                                 </g>
                                    <g>
                                 </g>
                                    <g>
                                 </g>
                                    <g>
                                 </g>
                                    <g>
                                 </g>
                                    <g>
                                 </g>
                                    <g>
                                 </g>
                                    <g>
                                 </g>
                                    <g>
                                 </g>
                                    <g>
                                 </g>
                                    <g>
                                 </g>
                                    <g>
                                 </g>
                                    <g>
                                 </g>
                                    <g>
                                 </g>
                                    <g>
                                 </g>
                                    <g>
                                 </g>
                              </svg>
                                </a>
                            </li>
                            <form class="form-inline">
                                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </button>
                            </form>
                        </ul>
                    </div>
                </nav>
            </div>
        </header>
        <!-- end header section -->
        @RenderSection("Slider", false)

    </div>



    <div class="container">
        @RenderBody()
    </div>


    <!-- footer start -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="full">
                        <div class="logo_footer">
                            <a href="#"><img width="210" src="~/images/corelogo.png" alt="#" /></a>
                        </div>
                        <div class="information_f">
                            <p><strong>ADDRESS:</strong> 1740 W 92nd ST #300, Kansas City, MO 64114</p>
                            <p><strong>TELEPHONE:</strong> (913) 322-7000</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-7">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="widget_menu">
                                        <h3>Menu</h3>
                                        <ul>
                                            @*TODO: Update footer links once pages have been created*@
                                            <li><a href="#">Home</a></li>
                                            <li><a href="#">Products</a></li>
                                            <li><a href="#">Contact</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="widget_menu">
                                        <h3>Account</h3>
                                        <ul>
                                            <li>
                                                <a asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Manage</a>
                                            </li>
                                            <li>
                                                <a asp-area="Identity" asp-page="/Account/Login">Login</a>
                                            </li>
                                            <li>
                                                <a asp-area="Identity" asp-page="/Account/Register">Register</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="widget_menu">
                                <h3>Newsletter</h3>
                                <div class="information_f">
                                    <p>Subscribe by our newsletter and get update protidin.</p>
                                </div>
                                <div class="form_sub">
                                    <form>
                                        <fieldset>
                                            <div class="field">
                                                <input type="email" placeholder="Enter Your Mail" name="email" />
                                                <input type="submit" value="Subscribe" />
                                            </div>
                                        </fieldset>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer end -->
    <div class="cpy_">
        <p class="mx-auto">
            © @DateTime.Now.Year All Rights Reserved By <a href="https://centriq.com/">Centriq Training</a><br>

            Template By <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>

        </p>
    </div>
    <!-- jQery -->
    <script src="~/js/jquery-3.4.1.min.js"></script>
    <!-- popper js -->
    <script src="~/js/popper.min.js"></script>
    <!-- bootstrap js -->
    <script src="~/js/bootstrap.js"></script>

    <!-- datatables js -->
    <script src="//cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>

    <!-- custom js -->
    <script src="~/js/custom.js"></script>

    @await RenderSectionAsync("Scripts", false)
</body>
</html>

Core2TP.UI.MVC/Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Core2TP.UI.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Core2TP.UI.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Core2TP.UI.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Core2TP.UI.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>